### ISSUE TITLE
Failed to create Klaviyo user with error: A user with the same user name or email already exists.

### ISSUE THREAD

**Issue by alexsmith2709** [klaviyo/magento2-klaviyo#113]
I have just installed this module and got to the "Setup Klayivo User" stage and no matter what username i choose, even leaving it as the default "klaviyo" i get the errror "Failed to create Klaviyo user with error: A user with the same user name or email already exists." My business only uses 1 email address.
I havent created a user before and this is a new installation of the klaviyo module.
I am using Magento 2.4.2 and kalviyo was installed using composer.

Thanks,
Alex

**Comment by klaviyojad** [comment]
@alexsmith2709 I apologize for this error that you are seeing.  Are you still able to create a new user by going to System > Users > Add New User and then giving the user a role having Resource > Access value of "All"  or at least selecting the following permissions: 

- Catalog > Inventory > Categories
- Carts > Manage Carts
- Customers > Customer Groups
- Customers > All Customers
- Sales > Operations > Orders > Actions > View
- Stores > Attributes > Product
- Catalog > Inventory > Products
- Sales > Operations > Shipments
- Stores > Settings > All Stores
- Marketing > Communications > Newsletter Subscribers

Then you could use these credentials for the Magento 2 Integration in Klaviyo as described [here](https://help.klaviyo.com/hc/en-us/articles/115005254348-How-to-Integrate-with-Magento-2-x-CE-and-EE-#enable-the-magento-2-integration-in-klaviyo5)

I want to also ask since you are on version 2.4.2 if you have Two-Factor Authentication on?  If so then then user api access from Klaviyo will not work and we will have to set you up with OAuth between Magento2 and Klaviyo.

**Comment by alexsmith2709** [comment]
Hi,
I just created a user with a personal email address to get around it. The other user i have using my one business email address is already an admin of magento so should have all permissions. I wasnt aware at the time that i could have used this user for kalviyo and not need a second account added.

**Comment by klaviyojad** [comment]
@alexsmith2709 sorry about the confusion.  The functionality from the Klaviyo plugin just creates a new Magento user and just ensures that the correct permissions are set for it.  Correct that you can just create them using the normal means or just reuse an already existing user.
