### ISSUE TITLE
Cannot Activate OAuth Magento 2.4.2

### ISSUE THREAD

**Issue by alexsmith2709** [klaviyo/magento2-klaviyo#122]
I have tried setting up OAuth in Magento 2.4.2 but it will not activate from System > Integrations. I get the error "Sorry, something went wrong. Please try again later." This happens every time i've tried.
I have 3.0.2 installed and upgraded to 3.0.3 so i could setup OAuth as Klaviyo was not detecting my install before (and still not). I have triple checked my API details and they are correct.

**Comment by pauloharaujos** [comment]
I have the same issue here. Magento version 2.4.2-p1

**Comment by klaviyojad** [comment]
@alexsmith2709 could you confirm that your server could make outgoing calls to https://www.klaviyo.com/integration-oauth-one/magento-two/auth/confirm?c=<Company ID> and https://www.klaviyo.com/integration-oauth-one/magento-two/auth/handle?  Otherwise could you please email us at extensions@klaviyo.com ?

**Comment by mathanagopaloxsoftwares** [comment]
@klaviyojad I am getting the same issue in our test server. When I click allow I am getting Sorry Something went wrong popup. The URL - _<store_admin_url>/admin/integration/tokensExchange/id/3/reauthorize/0/key/bd721b5136874cb42ec081a7fd4ff8b104eb6466ae15bd5d09dc5194bfe11111/?form_key=qzI7kZChJFKnjKRA&_=1624334731157_ is going to 404 error.

**Below is the screenshot of that error:**

![image](https://user-images.githubusercontent.com/76041988/122861781-a59e1a80-d33d-11eb-9fe0-92e2cca0cfe2.png)

**Version details:**
Magento 2.4.2
Klaviyo 3.0.5

One more thing. How to check the server could make outgoing calls to the URLs that are mentioned by you in the previous comment?
**Note**: Our test site is not having any htaccess password of any type.

**Comment by klaviyojad** [comment]
@mathanagopaloxsoftwares we figured out the cause of this problem.  It is due to a defect affecting Magento 2.4.2, it appears the next version they release will address it but in the meantime you can follow the recommendation [here ](https://magento.stackexchange.com/questions/323992/unable-to-activate-integration-with-oauth-1-0)

**Comment by mathanagopaloxsoftwares** [comment]
@klaviyojad Thanks for the quick response. We will try the solution.
