### ISSUE TITLE
Private API Key field in general settings is disabled

### ISSUE THREAD

**Issue by nawawishkid** [klaviyo/magento2-klaviyo#143]
Magento version: 2.4.1
Klaviyo version: 3.0.9

Installing with Composer
On a local machine with a custom domain name (.local)
No TLS/SSL certificate

I can’t follow the instruction from https://help.klaviyo.com/hc/en-us/articles/115005254348-How-to-Integrate-with-Magento-2-x-CE-and-EE-#install-with-composer--2-4--2 since the “Private Klaviyo API Key” field is disabled for no reason.

After Composer installation, I’ve already run:

`bin/magento module:enable Klaviyo_Reclaim --clear-static-content`
`bin/magento setup:upgrade`
`bin/magento setup:static-content:deploy -f`

![image](https://user-images.githubusercontent.com/71911303/139795346-dd8a6904-1d32-45f0-b529-6abe9c14a159.png)

The extension was enabled, the public key was set, and the configuration was saved. Still, the private API key is disabled. I’ve also tried uninstalling the extension and reinstalling it again using Composer. Nothing works.

I guess this is a bug. Otherwise, there should be a message indicating the reasons why the field is blocked.

Please help.

**Comment by klaviyojad** [comment]
@nawawishkid I believe your inquiry was responded to in the Klaviyo Community forums: https://community.klaviyo.com/integrations-39/magento-2-private-api-key-field-in-general-settings-is-disabled-2796?postid=10010#post10010
You will not get far with the setup as when you get to the setup oauth step it will not work because it requires a handshake process between the Klaviyo server and your localhost magento 2 server.  Let me know if you hit the same issue when you try this on your staging server.

**Comment by nawawishkid** [comment]
Okay. Thank you!
