### ISSUE TITLE
Not able to connect klaviyo to Magento Store

### ISSUE THREAD

**Issue by Shreyash1295** [klaviyo/magento2-klaviyo#256]
### Description

Hi I am Not able to connect my Magento 2 store 
**v2.4.3** to Klaviyo 
Once i create an integration with Magento after some time i get the following error
![Screenshot from 2023-05-23 18-12-37](https://github.com/klaviyo/magento2-klaviyo/assets/110890538/9b03515b-dad3-4cf5-b978-d0108950e2a5)
![Screenshot from 2023-05-23 18-10-17](https://github.com/klaviyo/magento2-klaviyo/assets/110890538/4e6b4977-2b19-4bd9-92a0-85c0997ba395)
it give 403 error that has no permission issue 
Can you please guide me of how to solve this issue as data is not going through klaviyo

**Comment by cykolln** [comment]
@Shreyash1295 Hello! This issue is better handled through Klaviyo support as they will be able to access your account details and thoroughly troubleshoot this specific issue with you. Please visit https://www.klaviyo.com/success or click through the support link on the top right of your screen on Klaviyo.
